settings:
    restrictions:
        # Can unregistered players chat, care , that block all commands except followers
        allowChat: false
        # Commands allowed when a player is unlogged
        allowCommands:
        - /login
        - /register
        - /l
        - /reg
        - /passpartu
        - /email
        - /captcha
        # Maximum Registraion per IP default: 1
        maxRegPerIp: 1
        # max allowed nick length (Warning when you use
        # mysql and choose a value >20 you have to 
        # increase the size of the nickname column in your
        # mysql table)
        maxNicknameLength: 16
        # Player that is online arent 
        # kick out for "logged in from another
        # Location", this options will prevent players that would exploit
        # your account when you are playing
        ForceSingleSession: true
        # For activate Restricted user by ip u need
        # to set True this option and configure the field
        # AllowedRestrctedUser as show below
        AllowRestrictedUser: false
        # Restricted user will kick players that 
        # is listed below and they dont
        # meet the match of username;ip
        # Example playername;127.0.0.1 , if playername 
        # hasent 127.0.0.1 as ip address
        # he will not be allowed to join the server
        AllowedRestrictedUser:
        - playername;127.0.0.1
        # Should unregistered players be kicked immediatly?
        kickNonRegistered: false
        # Should fail password players be kicked immediatly?
        kickOnWrongPassword: false
        # should not loged in players be teleported to spawn?
        # On login they will be teleported back to their normal
        # position
        teleportUnAuthedToSpawn: false
        # min allowed nick length 
        minNicknameLength: 3
        # Can unregistered players walk around?
        allowMovement: false
        # After what time players who fail to login or register
        # should be kicked. Set to 0 to disable.
        timeout: 30
        # Regex sintax for allowed Char in player name.
        allowedNicknameCharacters: '[a-zA-Z0-9_?]*'
        # How far can unregistered players walk? Set to 0
        # for unlimited radius
        allowedMovementRadius: 100
        # Enable double check of password when you register
        # when it's true, registration require that kind of command:
        # /register <password> <confirmPassword>
        enablePasswordVerifier: true
        # Should we protect the player inventory before logging in?
        ProtectInventoryBeforeLogIn: true
        # Should we display all other accounts from a player when he joins?
        # permission: /authme.admin.accounts
        displayOtherAccounts: true
        # WorldNames where we need to force the spawn location for ForceSpawnLocOnJoinEnabled
        # Ban ip when the ip is not the ip registered in database
        banUnsafedIP: false
    security:
        # minimum Length of password
        minPasswordLength: 4
        # possible values: MD5, SHA1, SHA256, WHIRLPOOL, XAUTH, MD5VB, PHPBB,
        # PLAINTEXT ( unhashed password),
        # SMF, SHA512,
        # DOUBLEMD5, PBKDF2, CUSTOM(for developers only)
        passwordHash: SHA256
        # If password checking return false , do we need to check with all
        # other password algorithm to check an old password ?
        # AuthMe will update the password to the new passwordHash !
        supportOldPasswordHash: false
    registration:
        # enable registration on the server?
        enabled: true
        # Send every X seconds a message to a player to
        # remind him that he has to login/register
        messageInterval: 5
        # Only registered and logged in players can play.
        # See restrictions for exceptions
        force: true
    unrestrictions:
        # below you can list all your account name, that
        # AuthMe will ignore for registration or login, configure it
        # at your own risk!! Remember that if you are going to add
        # nickname with [], you have to delimit name with ' '.
        # this option add compatibility with BuildCraft and some
        # other mods.
        # It is CaseSensitive!
        UnrestrictedName: []
    # Message language, available : en, de, br, cz, pl, fr, ru, hu, sk, es, zhtw, fi, zhcn, lt, it, ko, pt
    messagesLanguage: en
ExternalBoardOptions:
    # MySQL column for the salt , needed for some forum/cms support
    mySQLColumnSalt: ''
    # MySQL column for the group, needed for some forum/cms support
    mySQLColumnGroup: ''
    # -1 mean disabled. If u want that only
    # activated player can login in your server
    # u can put in this options the group number
    # of unactivated user, needed for some forum/cms support
    nonActivedUserGroup: -1
    # Other MySQL columns where we need to put the Username
    mySQLOtherUsernameColumns: []
    # How much Log to Round needed in BCrypt(do not change it if you do not know what's your doing)
    bCryptLog2Round: 10
    # phpBB prefix defined during phpbb installation process
    phpbbTablePrefix: 'phpbb_'
    # phpBB activated group id , 2 is default registered group defined by phpbb
    phpbbActivatedGroupId: 2
    # WordPress prefix defined during WordPress installation process
    wordpressTablePrefix: 'wp_'
BackupSystem:
   # Enable or Disable Automatic Backup
    ActivateBackup: false
   # set Backup at every start of Server
    OnServerStart: false
   # set Backup at every stop of Server
    OnServerStop: true
   # Windows only mysql installation Path
    MysqlWindowsPath: 'C:\\Program Files\\MySQL\\MySQL Server 5.1\\'
Passpartu:
    # Enable or Disable Passpartu Feature,
    # this feature let Admin Login with all registered 
    # Account they need, for example inspecting Player that
    # is doing shit, they can login without know any 
    # Player password! More info on How TO
    enablePasspartu: false
Security:
    SQLProblem:
        # Stop the server if we can't contact the sql database
        # Take care with this, if you set that to false,
        # AuthMe automatically disable and the server is not protected!
        stopServer: true
    console:
        # Remove spam console
        noConsoleSpam: false
        # Replace passwords in the console when player type a command like /login
        removePassword: true
    captcha:
        # Player need to put a captcha when he fails too lot the password
        useCaptcha: false
        # Max allowed tries before request a captcha
        maxLoginTry: 5
        # Captcha length
        captchaLength: 5
Converter:
    Rakamak:
        # Rakamak file name
        fileName: users.rak
        # Rakamak use ip ?
        useIP: false
        # IP file name for rakamak
        ipFileName: UsersIp.rak
        # possible values: MD5, SHA1, SHA256, WHIRLPOOL, XAUTH, MD5VB, PHPBB,
        # PLAINTEXT ( unhashed password),
        # MYBB, IPB3, PHPFUSION, SMF, XENFORO, SALTED2MD5, JOOMLA, BCRYPT, WBB3, SHA512,
        # DOUBLEMD5, PBKDF2, WORDPRESS, CUSTOM(for developpers only)
        newPasswordHash: SHA256
Hooks:
    # Do we need to hook with multiverse for spawn checking?
    multiverse: true
    # Do we need to hook with ChestShop for prevent buy or selling ?
    chestshop: true
    # Do we need to hook with Notifications for Notifs sending ?
    notifications: true
    # Do we need to disable Essentials SocialSpy on join ?
    disableSocialSpy: true
    # Do we need to force /motd Essentials command on join ?
    useEssentialsMotd: false
Protection:
    # Enable some servers protection ( country based login, antibot )
    enableProtection: false
    # Countries allowed to join the server and register, see http://dev.maxmind.com/geoip/legacy/codes/iso3166/ for countries' codes
    countries:
    - US
    - GB
    # Do we need to enable automatic antibot system?
    enableAntiBot: false
    # Max number of player allowed to login in 5 secs before enable AntiBot system automatically
    antiBotSensibility: 5
    # Duration in minutes of the antibot automatic system
    antiBotDuration: 10